### ISSUE TITLE
Extension causing Busy Server

### ISSUE THREAD

**Issue by asfixia** [terrabrasilis/geoserver-cluster#2]
I'm using the JMC Cluster for geoserver 2.18.0 , that i've downloaded from geoserver site.

I'm having two issues:
1º : After some time the geoserver stopped responding.
2º : When i restarted geoserver, after some minutes, the server was delaying his responses and returning "Busy server" on geoserver Web UI.

I dont know what happened but i could get geoserver working again only when i deleted the gs_data and the kahadb for all instances.

PS: My environment have two different machines in same LAN network, only one GS is "master" all others are "Slaves" instances.  I'm trying to share the same data dir. The slave instances we use to generate tile caches ( each of them using the embbedded GWC instances).
PS2: I saw that you have one commit removing GWC jars, this plugin has some trouble with GWC ?

**Comment by andre-carvalho** [comment]
Hi Danilo,

There are many variables related to the execution environment that impact the stability of the cluster.

To build your 2.18 GeoServer image, did you get the JMS compatible plugin from [the community directory](https://build.geoserver.org/geoserver/2.18.x/)?

At the moment, I don't use Broker to update my configuration changes.
After facing some instabilities in my cluster related to unstable network, I disabled the Broker and created a small script to call the reload catalog for each worker instance through the REST API after any configuration changes. In my case, settings are shared between all instances in the same data directory via NFS.

Another source of instability is related to cache data generated by GWC. To resolve these issues, I disabled the GWC index that I initially stored in a PostgreSQL database and disabled disk quota control.

And no less important is to define a load balancing installed in front of the cluster to distribute requests correctly and use the control flow plug-in to limit the maximum request that each instance can handle.

Response for PS2: Note that the line used to remove the GWC plugin is commented out. I did a test because, as I described above, some problem in my cluster was related to the GWC, but not the plugin itself, just some configuration incompatible with the cluster architecture.

It's not a specific issue in this repository, so if you find one, you can open a new ticket for it.

Grateful for the interest.
